#ifndef SHADER_H
#define SHADER_H

#ifdef SHADER_IMPLEMENTATION

// --- ЗАГАЛЬНИЙ ВЕРШИННИЙ ШЕЙДЕР ---
static const char *shader_vertex_source =
    "#version 120\n"
    "varying vec2 vTexCoord;\n"
    "void main() {\n"
    "    vTexCoord = gl_MultiTexCoord0.xy;\n"
    "    gl_Position = ftransform();\n"
    "}\n";
// --- БАЗОВИЙ ШЕЙДЕР МАСШТАБУВАННЯ (Режими 0, 1, 2, 3) ---
static const char *frag_basic_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "varying vec2 vTexCoord;\n"
    "vec2 getUV(vec2 tc) { return vec2(tc.x, 1.0 - tc.y); }\n"
    "void main() {\n"
    "    gl_FragColor = texture2D(screenTex, getUV(vTexCoord));\n"
    "}\n";

// --- ШЕЙДЕР CATMULL-ROM (Режим 4) ---
static const char *frag_catmull_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "varying vec2 vTexCoord;\n"
    "vec2 getUV(vec2 tc) { return vec2(tc.x, 1.0 - tc.y); }\n"
    "vec4 catmullRomWeights(float x) {\n"
    "    float x2 = x * x; float x3 = x2 * x;\n"
    "    return vec4(\n"
    "        -0.5 * x3 + 1.0 * x2 - 0.5 * x,\n"
    "         1.5 * x3 - 2.5 * x2 + 1.0,\n"
    "        -1.5 * x3 + 2.0 * x2 + 0.5 * x,\n"
    "         0.5 * x3 - 0.5 * x2\n"
    "    );\n"
    "}\n"
    "void main() {\n"
    "    vec2 uv = getUV(vTexCoord);\n"
    "    vec2 size = 1.0 / uTexelSize;\n"
    "    vec2 pos = uv * size - 0.5;\n"
    "    vec2 iPos = floor(pos);\n"
    "    vec2 fPos = fract(pos);\n"
    "    vec4 wX = catmullRomWeights(fPos.x);\n"
    "    vec4 wY = catmullRomWeights(fPos.y);\n"
    "    vec4 centerValue = vec4(0.0);\n"
    "    vec4 minColor = vec4(1.0);\n"
    "    vec4 maxColor = vec4(0.0);\n"
    "    for(int j = -1; j <= 2; j++) {\n"
    "        float wy = wY[j+1];\n"
    "        for(int i = -1; i <= 2; i++) {\n"
    "            float wx = wX[i+1];\n"
    "            vec2 sample_uv = (iPos + vec2(float(i), float(j)) + 0.5) * uTexelSize;\n"
    "            vec4 sample = texture2D(screenTex, sample_uv);\n"
    "            centerValue += sample * (wx * wy);\n"
    "            minColor = min(minColor, sample);\n"
    "            maxColor = max(maxColor, sample);\n"
    "        }\n"
    "    }\n"
    "    gl_FragColor = clamp(centerValue, minColor, maxColor);\n"
    "}\n";

// --- СУПЕР-ЧІТКИЙ АДАПТИВНИЙ ШЕЙДЕР ДЛЯ UI ТА ДРІБНИХ ОБ'ЄКТІВ ---
static const char *frag_fsr_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "varying vec2 vTexCoord;\n"
    "vec2 getUV(vec2 tc) { return vec2(tc.x, 1.0 - tc.y); }\n"
    "float getLuma(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }\n"
    "void main() {\n"
    "    vec2 uv = getUV(vTexCoord);\n"
    "    vec2 pos = uv / uTexelSize - 0.5;\n"
    "    vec2 iPos = floor(pos);\n"
    "    vec2 fPos = fract(pos);\n"
    "\n"
    "    // 1. Зчитуємо критичний мінімум - квадрат 2x2 навколо точки\n"
    "    vec4 p00 = texture2D(screenTex, (iPos + vec2(0.5, 0.5)) * uTexelSize);\n"
    "    vec4 p10 = texture2D(screenTex, (iPos + vec2(1.5, 0.5)) * uTexelSize);\n"
    "    vec4 p01 = texture2D(screenTex, (iPos + vec2(0.5, 1.5)) * uTexelSize);\n"
    "    vec4 p11 = texture2D(screenTex, (iPos + vec2(1.5, 1.5)) * uTexelSize);\n"
    "\n"
    "    // Обчислюємо локальні яскравості\n"
    "    float l00 = getLuma(p00.rgb); float l10 = getLuma(p10.rgb);\n"
    "    float l01 = getLuma(p01.rgb); float l11 = getLuma(p11.rgb);\n"
    "\n"
    "    // Знаходимо локальний контраст у квадраті 2x2\n"
    "    float minLuma = min(min(l00, l10), min(l01, l11));\n"
    "    float maxLuma = max(max(l00, l10), max(l01, l11));\n"
    "    float localContrast = maxLuma - minLuma;\n"
    "\n"
    "    // 2. ДИНАМІЧНА КОРЕКЦІЯ КООРДИНА (Захист дрібних деталей)\n"
    "    // Якщо контраст дуже високий (дрібний текст/іконка, ми робимо криву переходу\n"
    "    // надзвичайно крутою за допомогою smoothstep. Це не дає пікселям «повзти» вбік.\n"
    "    vec2 fPosAdjusted = fPos;\n"
    "    if (localContrast > 0.15) {\n"
    "        float strength = smoothstep(0.15, 0.6, localContrast);\n"
    "        // Надважлива математика: підтискаємо інтерполяцію до центрів оригінальних пікселів\n"
    "        fPosAdjusted.x = mix(fPos.x, smoothstep(0.0, 1.0, fPos.x), strength);\n"
    "        fPosAdjusted.y = mix(fPos.y, smoothstep(0.0, 1.0, fPos.y), strength);\n"
    "    }\n"
    "\n"
    "    // 3. Виконуємо високоточну кубічну інтерполяцію (Bicubic Hermite) за скоригованими координатами\n"
    "    vec2 w0 = fPosAdjusted * fPosAdjusted * (3.0 - 2.0 * fPosAdjusted);\n"
    "    \n"
    "    vec4 mixX1 = mix(p00, p10, w0.x);\n"
    "    vec4 mixX2 = mix(p01, p11, w0.x);\n"
    "    vec4 finalColor = mix(mixX1, mixX2, w0.y);\n"
    "\n"
    "    // 4. ЗАЛІЗОБЕТОННЕ ОБМЕЖЕННЯ (Anti-Bleeding)\n"
    "    // Повністю виключає появу сірого туману чи сторонніх кольорів навколо літер\n"
    "    vec4 minColor = min(min(p00, p10), min(p01, p11));\n"
    "    vec4 maxColor = max(max(p00, p10), max(p01, p11));\n"
    "    \n"
    "    gl_FragColor = clamp(finalColor, minColor, maxColor);\n"
    "}\n";
// --- АДАПТИВНИЙ ШЕЙДЕР БЕЗ ФЛІПУ ДЛЯ РЕЖИМУ 7 ---
static const char *frag_fsr_no_flip_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "varying vec2 vTexCoord;\n"
    "float getLuma(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }\n"
    "void main() {\n"
    "    vec2 uv = vTexCoord;\n"
    "    vec2 pos = uv / uTexelSize - 0.5;\n"
    "    vec2 iPos = floor(pos);\n"
    "    vec2 fPos = fract(pos);\n"
    "\n"
    "    // 1. Зчитуємо критичний мінімум - квадрат 2x2 навколо точки\n"
    "    vec4 p00 = texture2D(screenTex, (iPos + vec2(0.5, 0.5)) * uTexelSize);\n"
    "    vec4 p10 = texture2D(screenTex, (iPos + vec2(1.5, 0.5)) * uTexelSize);\n"
    "    vec4 p01 = texture2D(screenTex, (iPos + vec2(0.5, 1.5)) * uTexelSize);\n"
    "    vec4 p11 = texture2D(screenTex, (iPos + vec2(1.5, 1.5)) * uTexelSize);\n"
    "\n"
    "    // Обчислюємо локальні яскравості\n"
    "    float l00 = getLuma(p00.rgb); float l10 = getLuma(p10.rgb);\n"
    "    float l01 = getLuma(p01.rgb); float l11 = getLuma(p11.rgb);\n"
    "\n"
    "    // Знаходимо локальний контраст у квадраті 2x2\n"
    "    float minLuma = min(min(l00, l10), min(l01, l11));\n"
    "    float maxLuma = max(max(l00, l10), max(l01, l11));\n"
    "    float localContrast = maxLuma - minLuma;\n"
    "\n"
    "    // 2. ДИНАМІЧНА КОРЕКЦІЯ КООРДИНА (Захист дрібних деталей)\n"
    "    // Якщо контраст дуже високий (дрібний текст/іконка, ми робимо криву переходу\n"
    "    // надзвичайно крутою за допомогою smoothstep. Це не дає пікселям «повзти» вбік.\n"
    "    vec2 fPosAdjusted = fPos;\n"
    "    if (localContrast > 0.15) {\n"
    "        float strength = smoothstep(0.15, 0.6, localContrast);\n"
    "        // Надважлива математика: підтискаємо інтерполяцію до центрів оригінальних пікселів\n"
    "        fPosAdjusted.x = mix(fPos.x, smoothstep(0.0, 1.0, fPos.x), strength);\n"
    "        fPosAdjusted.y = mix(fPos.y, smoothstep(0.0, 1.0, fPos.y), strength);\n"
    "    }\n"
    "\n"
    "    // 3. Виконуємо високоточну кубічну інтерполяцію (Bicubic Hermite) за скоригованими координатами\n"
    "    vec2 w0 = fPosAdjusted * fPosAdjusted * (3.0 - 2.0 * fPosAdjusted);\n"
    "    \n"
    "    vec4 mixX1 = mix(p00, p10, w0.x);\n"
    "    vec4 mixX2 = mix(p01, p11, w0.x);\n"
    "    vec4 finalColor = mix(mixX1, mixX2, w0.y);\n"
    "\n"
    "    // 4. ЗАЛІЗОБЕТОННЕ ОБМЕЖЕННЯ (Anti-Bleeding)\n"
    "    // Повністю виключає появу сірого туману чи сторонніх кольорів навколо літер\n"
    "    vec4 minColor = min(min(p00, p10), min(p01, p11));\n"
    "    vec4 maxColor = max(max(p00, p10), max(p01, p11));\n"
    "    \n"
    "    gl_FragColor = clamp(finalColor, minColor, maxColor);\n"
    "}\n";
// --- ШЕЙДЕР ДЕНОІЗИНГУ (Режим 6) ---
static const char *frag_denoise_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "varying vec2 vTexCoord;\n"
    "vec2 getUV(vec2 tc) { return vec2(tc.x, 1.0 - tc.y); }\n"
    "float getLuma(vec3 color) { return dot(color, vec3(0.299, 0.587, 0.114)); }\n"
    "void main() {\n"
    "    vec2 uv = getUV(vTexCoord);\n"
    "    vec4 center = texture2D(screenTex, uv);\n"
    "    float centerLuma = getLuma(center.rgb);\n"
    "    vec4 sum = vec4(0.0);\n"
    "    float totalWeight = 0.0;\n"
    "    float sigmaSpace = 2.0;\n"
    "    float sigmaColor = 0.1;\n"
    "    for(int j = -2; j <= 2; j++) {\n"
    "        for(int i = -2; i <= 2; i++) {\n"
    "            vec2 offset = vec2(float(i), float(j));\n"
    "            vec2 sampleUv = uv + offset * uTexelSize;\n"
    "            vec4 sample = texture2D(screenTex, sampleUv);\n"
    "            float sampleLuma = getLuma(sample.rgb);\n"
    "            float spaceDist = length(offset);\n"
    "            float colorDist = abs(centerLuma - sampleLuma);\n"
    "            float wSpace = exp(-(spaceDist * spaceDist) / (2.0 * sigmaSpace * sigmaSpace));\n"
    "            float wColor = exp(-(colorDist * colorDist) / (2.0 * sigmaColor * sigmaColor));\n"
    "            float weight = wSpace * wColor;\n"
    "            sum += sample * weight;\n"
    "            totalWeight += weight;\n"
    "        }\n"
    "    }\n"
    "    gl_FragColor = sum / totalWeight;\n"
    "}\n";
// --- ШЕЙДЕР ПОСТ-ОБРОБКИ ТА RCAS (Pass 2) ---
static const char *post_fragment_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "uniform float uSharpness;\n"
    "uniform float uContrast;\n"
    "uniform float uBrightness;\n"
    "uniform float uGammaValue;\n"
    "uniform int uTextMode;\n"
    "uniform float uZoomLevel;\n"
    "varying vec2 vTexCoord;\n"
    "vec4 sharpenAdaptive(vec4 centerColor, vec2 uv) {\n"
    "    vec4 l = texture2D(screenTex, uv + vec2(-uTexelSize.x, 0.0));\n"
    "    vec4 r = texture2D(screenTex, uv + vec2(uTexelSize.x, 0.0));\n"
    "    vec4 u = texture2D(screenTex, uv + vec2(0.0, -uTexelSize.y));\n"
    "    vec4 d = texture2D(screenTex, uv + vec2(0.0, uTexelSize.y));\n"
    "    vec4 blur = (l + r + u + d) * 0.25;\n"
    "    vec4 minN = min(centerColor, min(min(l, r), min(u, d)));\n"
    "    vec4 maxN = max(centerColor, max(max(l, r), max(u, d)));\n"
    "    vec4 edgeDiff = maxN - minN;\n"
    "    float maxEdge = max(max(edgeDiff.r, edgeDiff.g), edgeDiff.b);\n"
    "    float adaptiveSharp = uSharpness * clamp(1.0 - maxEdge, 0.0, 1.0);\n"
    "    return centerColor + (centerColor - blur) * adaptiveSharp;\n"
    "}\n"
    "void main() {\n"
    "    vec2 uv = vTexCoord;\n"
    "    vec4 color = texture2D(screenTex, uv);\n"
    "    vec4 left  = texture2D(screenTex, uv + vec2(-uTexelSize.x, 0.0));\n"
    "    vec4 right = texture2D(screenTex, uv + vec2(uTexelSize.x, 0.0));\n"
    "    vec4 up    = texture2D(screenTex, uv + vec2(0.0, -uTexelSize.y));\n"
    "    vec4 down  = texture2D(screenTex, uv + vec2(0.0, uTexelSize.y));\n"
    "    vec4 blur = (left + right + up + down) * 0.25;\n"
    "    float zoomSharpness = uZoomLevel > 1.2 ? uSharpness : uSharpness * 0.35;\n"
    "    if (uSharpness > 0.0) color = color + (color - blur) * zoomSharpness;\n"
    "    if (uTextMode == 1) {\n"
    "        float luma = dot(color.rgb, vec3(0.299, 0.587, 0.114));\n"
    "        vec3 gray = vec3(luma);\n"
    "        color.rgb = mix(color.rgb, gray, 0.20);\n"
    "        vec4 textEdge = clamp((color - blur) * 2.5, -0.15, 0.15);\n"
    "        color.rgb += textEdge.rgb;\n"
    "        color.rgb = (color.rgb - 0.5) * 1.15 + 0.5;\n"
    "    }\n"
    "    color.rgb = (color.rgb - 0.5) * uContrast + 0.5 + uBrightness;\n"
    "    color.rgb = pow(clamp(color.rgb, 0.0, 1.0), vec3(1.0 / uGammaValue));\n"
    "    gl_FragColor = vec4(clamp(color.rgb, 0.0, 1.0), color.a);\n"
    "}\n";
// --- ШЕЙДЕР CAS ШАРПЕНІНГУ для Mode 7 ---
static const char *frag_cas_sharpen_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "uniform int uTextMode;\n"
    "varying vec2 vTexCoord;\n"
    "float getLuma(vec3 color) { return dot(color, vec3(0.299, 0.587, 0.114)); }\n"
    "void main() {\n"
    "    vec2 uv = vTexCoord;\n"
    "    vec4 c = texture2D(screenTex, uv);\n"
    "    vec4 n = texture2D(screenTex, uv + vec2(0.0, -uTexelSize.y));\n"
    "    vec4 s = texture2D(screenTex, uv + vec2(0.0, uTexelSize.y));\n"
    "    vec4 e = texture2D(screenTex, uv + vec2(uTexelSize.x, 0.0));\n"
    "    vec4 w = texture2D(screenTex, uv + vec2(-uTexelSize.x, 0.0));\n"
    "    vec4 minN = min(c, min(min(n, s), min(e, w)));\n"
    "    vec4 maxN = max(c, max(max(n, s), max(e, w)));\n"
    "    float maxEdge = max(max(maxN.r - minN.r, maxN.g - minN.g), maxN.b - minN.b);\n"
    "    float sharpStrength = clamp(maxEdge * 2.0, 0.0, 0.5);\n"
    "    vec4 avg = (n + s + e + w) * 0.25;\n"
    "    vec4 color = c + (c - avg) * sharpStrength;\n"
    "    if (uTextMode == 1) {\n"
    "        float luma = dot(color.rgb, vec3(0.299, 0.587, 0.114));\n"
    "        vec3 gray = vec3(luma);\n"
    "        color.rgb = mix(color.rgb, gray, 0.20);\n"
    "        vec4 textEdge = clamp((color - avg) * 2.5, -0.15, 0.15);\n"
    "        color.rgb += textEdge.rgb;\n"
    "        color.rgb = (color.rgb - 0.5) * 1.15 + 0.5;\n"
    "    }\n"
    "    gl_FragColor = color;\n"
    "}\n";
// --- РЕЖИМ 8: ГІБРИДНИЙ ДЕНОЙЗ + АДАПТИВНИЙ UI АПСКЕЙЛЕР ---
static const char *frag_hybrid_source =
    "#version 120\n"
    "uniform sampler2D screenTex;\n"
    "uniform vec2 uTexelSize;\n"
    "varying vec2 vTexCoord;\n"
    "vec2 getUV(vec2 tc) { return vec2(tc.x, 1.0 - tc.y); }\n"
    "float getLuma(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }\n"
    "void main() {\n"
    "    vec2 uv = getUV(vTexCoord);\n"
    "    vec2 pos = uv / uTexelSize - 0.5;\n"
    "    vec2 iPos = floor(pos);\n"
    "    vec2 fPos = fract(pos);\n"
    "\n"
    "    vec4 p00 = texture2D(screenTex, (iPos + vec2(0.5, 0.5)) * uTexelSize);\n"
    "    vec4 p10 = texture2D(screenTex, (iPos + vec2(1.5, 0.5)) * uTexelSize);\n"
    "    vec4 p01 = texture2D(screenTex, (iPos + vec2(0.5, 1.5)) * uTexelSize);\n"
    "    vec4 p11 = texture2D(screenTex, (iPos + vec2(1.5, 1.5)) * uTexelSize);\n"
    "\n"
    "    vec4 p0m1 = texture2D(screenTex, (iPos + vec2(0.5, -0.5)) * uTexelSize);\n"
    "    vec4 pm10 = texture2D(screenTex, (iPos + vec2(-0.5, 0.5)) * uTexelSize);\n"
    "    vec4 p20  = texture2D(screenTex, (iPos + vec2(2.5, 0.5)) * uTexelSize);\n"
    "    vec4 p02  = texture2D(screenTex, (iPos + vec2(0.5, 2.5)) * uTexelSize);\n"
    "\n"
    "    float l00 = getLuma(p00.rgb); float l10 = getLuma(p10.rgb);\n"
    "    float l01 = getLuma(p01.rgb); float l11 = getLuma(p11.rgb);\n"
    "\n"
    "    vec4 minColor = min(min(p00, p10), min(p01, p11));\n"
    "    vec4 maxColor = max(max(p00, p10), max(p01, p11));\n"
    "    float localContrast = max(max(max(l00, l10), l01), l11) - min(min(min(l00, l10), l01), l11);\n"
    "\n"
    "    float denoiseWeight = 1.0 - smoothstep(0.2, 0.6, localContrast);\n"
    "    if (denoiseWeight > 0.01) {\n"
    "        float w0m1 = exp(-abs(getLuma(p0m1.rgb) - l00) * 8.0);\n"
    "        float wm10 = exp(-abs(getLuma(pm10.rgb) - l00) * 8.0);\n"
    "        p00.rgb = mix(p00.rgb, (p00.rgb + p0m1.rgb * w0m1 + pm10.rgb * wm10) / (1.0 + w0m1 + wm10), denoiseWeight);\n"
    "        float w20 = exp(-abs(getLuma(p20.rgb) - l10) * 8.0);\n"
    "        p10.rgb = mix(p10.rgb, (p10.rgb + p20.rgb * w20) / (1.0 + w20), denoiseWeight);\n"
    "        float w02 = exp(-abs(getLuma(p02.rgb) - l01) * 8.0);\n"
    "        p01.rgb = mix(p01.rgb, (p01.rgb + p02.rgb * w02) / (1.0 + w02), denoiseWeight);\n"
    "    }\n"
    "\n"
    "    vec2 fPosAdjusted = fPos;\n"
    "    if (localContrast > 0.12) {\n"
    "        float uiStrength = smoothstep(0.12, 0.5, localContrast);\n"
    "        fPosAdjusted.x = mix(fPos.x, smoothstep(0.0, 1.0, fPos.x), uiStrength);\n"
    "        fPosAdjusted.y = mix(fPos.y, smoothstep(0.0, 1.0, fPos.y), uiStrength);\n"
    "    }\n"
    "\n"
    "    vec2 w = fPosAdjusted * fPosAdjusted * (3.0 - 2.0 * fPosAdjusted);\n"
    "    vec4 mixX1 = mix(p00, p10, w.x);\n"
    "    vec4 mixX2 = mix(p01, p11, w.x);\n"
    "    vec4 finalColor = mix(mixX1, mixX2, w.y);\n"
    "\n"
    "    gl_FragColor = clamp(finalColor, minColor, maxColor);\n"
    "}\n";

#endif
#endif 

